services:
  db:
    image: postgres:16
    container_name: superbowl-db
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=superbowl
    ports:
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    container_name: server
    build:
      context: ./apps/server/
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_DEBUG=1
      - FLASK_APP=./app.py
      - GNEWS=f5444f988fdaf431a788e80c3ab36465
      - DEVELOPMENT_DATABASE_URL=postgresql+psycopg2://postgres:password@superbowl-db:5432/superbowl
      - CONFIG_MODE=development
    networks:
      - app-network
    depends_on:
      - db

  client:
    container_name: client
    build:
      context: ./apps/client/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./apps/client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - app-network
    depends_on:
      - server

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
